resolver: lts-13.16

packages:
- "."

extra-deps:
- stm-containers-1.1.0.2
- stm-hamt-1.2.0.2
- primitive-extras-0.7.1
- happstack-server-tls-7.1.6.7
- happstack-server-7.5.1.3
- git: https://github.com/haskus/packages.git
  commit: 785f05a4bf8a44292c7419114190ce8eb9c8f83c
  subdirs:
     - haskus-utils-variant
     - haskus-utils
     - haskus-utils-types
     - haskus-utils-compat
     - haskus-utils-data
     - haskus-binary


ghc-options:
   "$locals": -fhide-source-paths -freverse-errors

build:
   interleaved-output: true
